chore; Change Application opened to application became active for native events
PostHog/posthog-js-lite pull request #211
Opened 2024-03-25 08:56 UTC by marandaneto

## Problem

Closes https://github.com/PostHog/posthog-js-lite/issues/144

## Changes

## Release info Sub-libraries affected

### Bump level

- [ ] Major
- [ ] Minor
- [ ] Patch

### Libraries affected

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

### Changelog notes

- Added support for X

2024-03-25 09:24 UTC, marandaneto commented on posthog-react-native/src/frameworks/wix-navigation.ts
> +    posthog.capture('Application Opened', {
All events already contain `$app_build` and `$app_version` but for some reason (maybe legacy props), all the other SDKs were sending `version` and `build` as well for the lifecycle events.

2024-03-25 09:26 UTC, marandaneto commented on posthog-react-native/src/frameworks/wix-navigation.ts
> +    posthog.capture('Application Opened', {
An option is to remove `version` and `build` from all those events as well, the mobile dashboards just rely on `$app_version` anyway, not sure if there's any other feature I am unaware of.

2024-03-25 09:30 UTC, benjackwhite requested changes

2024-03-26 12:57 UTC, benjackwhite commented on posthog-react-native/src/hooks/useLifecycleTracker.ts
> +          })
Eugh. Personally I'd much rather align around $ properties than this change as it feels really un-posthog.

Would it be possible to do the opposite? Change the other SDKs to include the $ versions?

2024-03-26 13:10 UTC, marandaneto commented on posthog-react-native/src/hooks/useLifecycleTracker.ts
> +          })
removed them, will remove in the next major, and added a deprecated comment

2024-03-26 13:15 UTC, marandaneto commented on posthog-react-native/src/frameworks/wix-navigation.ts
> +    posthog.capture('Application Opened', {
Will remove them in the next major https://github.com/PostHog/posthog-js-lite/issues/212

2024-03-26 13:15 UTC, merged