feat: allow API host as config option
PostHog/posthog-js-lite pull request #87
Opened 2023-03-28 03:10 UTC by pauldambra

## Problem

In this community slack thread, the user points out we have confusingly similar init options https://posthogusers.slack.com/archives/CTLTM70RM/p1679968951879879

```
//(Basic) Initialization of posthog-js:
const posthog = new PostHog(env.POSTHOG_KEY, {
    api_host: env.POSTHOG_HOST
});
//(Basic) Initialization of posthog-node:
const posthog = new PostHog(env.POSTHOG_KEY, {
    host: env.POSTHOG_HOST
});
```

Note one is `host` and the other `api_host`

## Changes

Allows you to init posthog-node (and other libraries that use posthog-core) with **either** `host` or `api_host`

## Release info Sub-libraries affected

### Bump level

- [ ] Major
- [x] Minor
- [ ] Patch

### Libraries affected

- [x] All of them
- [ ] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

### Changelog notes

- Added support for initialising using either `host` or `api_host` as the key to config the posthog URL for the library

2023-03-29 00:42 UTC, benjackwhite requested changes
I think this is a clever approach but possibly the wrong one...

I think this will lead to _more_ confusion - "which should I use? What's the difference?" type questions. The answer of "someone got confused with our other SDK and so we added support for both" is I think more confusing 😅

Either we should just accept that the libs are different or decide we want to standardise on api_host and add that as a new optional property and mark the old one as deprecated. We then simply say "api_host" takes priority over "host" and then simplify all the types.

2023-03-29 01:39 UTC, pauldambra commented on posthog-core/src/index.ts
> +}
IIUC the types I declared don't let you do `options?.host || options?.api_host || undefined` it doesn't know if host or api_host is in the type

You can't declare `api_host` and `host` so if you declare `host: undefined` then we accept that and end up using the default (as without this change)

2023-03-29 01:40 UTC, pauldambra commented on posthog-core/src/index.ts
> +}
but...

>we should just accept that the libs are different or decide we want to standardise on api_host and add that as a new optional property and mark the old one as deprecated. We then simply say "api_host" takes priority over "host" and then simplify all the types.

👍

2023-03-29 01:49 UTC, neilkakkar commented
Don't like supporting both options with priority to one either, that will just turn into a mess over time 😬 .

The pain here is more general: mistyping config keys just implies the 'right' key is undefined/default, when that shouldn't be the case.

2023-03-29 03:19 UTC, pauldambra commented
@neilkakkar so the direction over time would be to replace `api_host` with `host` everywhere? (that is posthog-js is "wrong" not posthog-node)

2023-03-30 02:16 UTC, neilkakkar commented
If we have to, yes

2023-03-30 02:52 UTC, closed without merging